### ISSUE TITLE
Where can I get vocab.json of "japanese-stable-diffusion"'s tokenizer

### ISSUE THREAD

**Issue by svjack** [rinnakk/japanese-stable-diffusion#6]
I look a load script in https://github.com/huggingface/diffusers/tree/60c384bcd2b6f0cf9569fa8999ac8f7eff98b31a/examples/text_to_image

and try to use the following code snippet to load downloaded "japanese-stable-diffusion"
```python
tokenizer = CLIPTokenizer.from_pretrained(args.pretrained_model_name_or_path, subfolder="tokenizer")
text_encoder = CLIPTextModel.from_pretrained(args.pretrained_model_name_or_path, subfolder="text_encoder")
vae = AutoencoderKL.from_pretrained(args.pretrained_model_name_or_path, subfolder="vae")
unet = UNet2DConditionModel.from_pretrained(args.pretrained_model_name_or_path, subfolder="unet")
```
CLIPTokenizer.from_pretrained yield a error
in the tokenizer path downloaded contains
```bash
special_tokens_map.json	
spiece.model		
tokenizer_config.json
```
But in stable-diffusion-v1-4's tokenizer path downloaded contains
```bash
merges.txt		
tokenizer_config.json
special_tokens_map.json	
vocab.json
```

the absent  of vocab.json yield error when use CLIPTokenizer.from_pretrained to load "japanese-stable-diffusion"
where can I get "vocab.json" file

**Comment by mkshing** [comment]
@svjack Hi, our Japanese tokenizer is based on sentencepiece tokenizer. So, you can load by using `T5Tokenizer` instead of `CLIPTokenizer`.
```python
tokenizer = T5Tokenizer.from_pretrained(args.pretrained_model_name_or_path, subfolder="tokenizer")
text_encoder = CLIPTextModel.from_pretrained(args.pretrained_model_name_or_path, subfolder="text_encoder")
vae = AutoencoderKL.from_pretrained(args.pretrained_model_name_or_path, subfolder="vae")
unet = UNet2DConditionModel.from_pretrained(args.pretrained_model_name_or_path, subfolder="unet")
```
