### ISSUE TITLE
KeyError in scripts/txt2img.ipynb

### ISSUE THREAD

**Issue by sue1242** [rinnakk/japanese-stable-diffusion#7]
When I ran scripts/txt2img.ipynb, I got following KeyError;
 
```
  File "<ipython-input-11-72e14649136e>", line 27, in infer
    )["sample"]
  File "/usr/local/lib/python3.7/dist-packages/diffusers/utils/outputs.py", line 88, in __getitem__
    return inner_dict[k]
KeyError: 'sample'
```

Is the correct key "images" instead of "sample"?

**Comment by matsurih** [comment]
Same, I created PR to fix this error.

**Comment by sue1242** [comment]
@matsurih 
Thanks.

By the way, I don't know how to create PR in OSS repository. Could you tell me how did you create PR?
Can I create PR by following way?
https://qiita.com/y-vectorfield/items/b955617712f3b66359f2

**Comment by mkshing** [comment]
@matsurih Thank you for your contribution! I merged your PR.
